# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0002_auto_20170108_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('address', models.CharField(max_length=1000)),
                ('more_info_url', models.TextField()),
                ('w_date', models.DateField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('passthru', models.BooleanField()),
                ('travel_mode', models.CharField(max_length=100)),
                ('travel_path', models.CharField(max_length=100)),
                ('travel_dest', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='scr_id',
            new_name='src_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='jb',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='published_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtrip.Trip'),
        ),
    ]
