# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0003_auto_20170108_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='finished',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='started',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
