# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0004_auto_20170108_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
