# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0005_auto_20170108_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='follow_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='thumbnail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
