# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0006_auto_20170108_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
