# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0007_trip_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='w_date',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='w_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='more_info_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='passthru',
            field=models.BooleanField(default=None),
        ),
    ]
