# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0011_auto_20170108_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='travel_dest',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='travel_mode',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
