# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0013_auto_20170108_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='waypoint',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='showtrip.Country'),
        ),
    ]
