# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0014_auto_20170110_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='good_point_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
