# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0015_trip_good_point_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_country', to='showtrip.Country')),
                ('waypoint_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_waypoint_type', to='showtrip.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PointName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('point', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointname_point', to='showtrip.Point')),
            ],
        ),
        migrations.CreateModel(
            name='WaypointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='waypoint',
            name='point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_point', to='showtrip.Country'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='waypoint_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_waypoiny_type', to='showtrip.Country'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_country', to='showtrip.Country'),
        ),
    ]
