# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0016_auto_20170110_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='point',
            name='lng',
        ),
        migrations.AddField(
            model_name='pointname',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointname',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
