# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0017_auto_20170110_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointname',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
