# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0018_pointname_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
