# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0019_auto_20170110_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
