# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0021_auto_20170110_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('distance', models.FloatField(blank=True, default=None, null=True)),
                ('point', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trippoint_point', to='showtrip.Point')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtrip.Trip')),
            ],
        ),
    ]
