# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0022_trippoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippoint',
            name='thumbnail',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
