# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0024_auto_20170110_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='orderby',
            field=models.IntegerField(default=0),
        ),
    ]
