# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0026_auto_20170110_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pointsbitmap',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
