# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtrip', '0027_auto_20170110_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(default=0),
        ),
    ]
